### ISSUE TITLE
Implement support for non-nil exit code

### ISSUE THREAD

**Issue by ourbjorn** [praetorian-inc/gokart#17]
Hi!

To ease the use of this tool in automated systems such as CI/CD, and enable an optional failure mode on possible vulnerability findings, I suggest to implement a new boolean argument such as in #9 .

With a non-nil exit code the CI/CD can stop pipelines and jobs easily when a potential vulnerability is found.

**Comment by michaelweber** [comment]
Thanks for opening an issue for this @ourbjorn!

I think this is going to be a pretty common use case for `gokart`, so we'll likely be working on making it easier to integrate into a CI/CD pipeline sooner than later.

**Comment by 030** [comment]
@michaelweber Could you indicate in what version this feature will become available?

**Comment by isp1r0** [comment]
@030 just wanted to point out that this feature, along with several more enhancements to integration into CI/CD pipelines have been added in the last couple of weeks.  Let us know what you think when you get a chance!

**Comment by 030** [comment]
@isp1r0 Did you create a new release? The current version 0.2.0 was created 22 days ago while the merge request was merged 16 days ago.
