### ISSUE TITLE
Publish gokart in docker github packages

### ISSUE THREAD

**Issue by renanpalmeira** [praetorian-inc/gokart#26]
do you think it makes sense to post a gokart docker image in github packages? I really like the idea of ​​this type of tool that I can use `docker run praetorian-inc/gokart scan ...`

I even have something very similar here https://github.com/renanpalmeira/docker-protobufs/pkgs/container/protobuf

on a daily basis I end up using it like this: 

```
docker run --rm \
    --name my-protos \
    -u $(id -u):$(id -u) \
    -v `pwd`:/code \
    ghcr.io/renanpalmeira/protobuf:latest \
        --proto_path=/code/protos \
        --go_out=plugins=grpc,paths=source_relative:/code/protos/gen \
        /code/protos/*.proto
```

**Comment by isp1r0** [comment]
@renanpalmeira Yes, we agree 💯  There were a couple pieces missing in the initial release that prevented us from including docker support.  The first was the lack of output to a file which was just added and merged in https://github.com/praetorian-inc/gokart/pull/24 and the other is remote repo scanning which is in review https://github.com/praetorian-inc/gokart/pull/20

Once these are in place, we'll have everything we need to either scan a local repo by mounting it or cloning directly to the container for the scan.  In either case, we will be able to output results to the current directory.  

Thanks for the great suggestion!

**Comment by isp1r0** [comment]
Many thanks to @praetorian-thendrickson for adding this feature!!  

@renanpalmeira take it out for spin when you get a chance :)

**Comment by renanpalmeira** [comment]
OWOOO sorry for the delay, now that I saw it! I'll test now! Thank you very much 👏👏👏👏👏👏👏👏👏👏

cc: @isp1r0 @praetorian-harry
