### ISSUE TITLE
Add command line flag to write out findings to file

### ISSUE THREAD

**Issue by isp1r0** [praetorian-inc/gokart#3]
As a developer looking to add GoKart into my CI/CD pipeline integration, I need a way to output findings to a file.

Proposed solution: Adding a new command line flag: -o, -output 

Details: 

- Flag should  take an optional argument of <filename> for text file to write to
- If optional argument is missing, default to a reasonable, unique name
- Redirect console output to file to preserve other flag functionality 

Alternatives to consider:
- Write out findings in a standard json format rather than directly to a text file, limiting the scope to the standard 'scan' output
- Require a user provided <filename> argument, alleviating the need for default naming logic

**Comment by michaelweber** [comment]
I'm going to require a user argument for this, if someone wants an output file they can provide the filename - I don't think we want to worry about naming conventions.

**Comment by isp1r0** [comment]
This feature is working great @michaelweber!  Closing this issue.
