### ISSUE TITLE
you forgot to update the version to 0.5.0

### ISSUE THREAD

**Issue by cmaurer** [praetorian-inc/gokart#81]
https://github.com/praetorian-inc/gokart/blob/main/cmd/version.go
https://github.com/praetorian-inc/gokart/blob/v0.5.0/cmd/version.go

**Comment by praetorian-harry** [comment]
@cmaurer thank you! I've pushed a new release to address this: https://github.com/praetorian-inc/gokart/releases/tag/v0.5.1
